"""empty message

Revision ID: 4bad1780abf2
Revises: 2b3cf778cc2f
Create Date: 2025-12-06 03:48:18.416716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bad1780abf2'
down_revision = '2b3cf778cc2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relation', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('url_img', sa.String(length=899), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_img', sa.String(length=899), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('url_img')

    with op.batch_alter_table('contactos', schema=None) as batch_op:
        batch_op.drop_column('url_img')
        batch_op.drop_column('relation')

    # ### end Alembic commands ###
